#!/bin/bash
while inotifywait -e close_write desorp_input.log
do
  RUN=$(tail -n 1 desorp.log)
  
  modify_input_file input.json implant_sub.i
  modify_input_file input.json resting_multi.i
  modify_input_file input.json desorp_multi.i

  achlys -i desorp_multi.i >> /dev/null

  stack_outputs result.csv
  
  mkdir results/$RUN
  cp input.json result.csv results/$RUN
  
  echo $RUN >> desorp_output.log
done
